Jahia/jcontent

src/javascript/ContentManager/ContentManager.redux-actions.js
src/javascript/ContentManager/ContentManager.redux-reducers.js
src/javascript/ContentManager/ContentManager.redux-store.js
src/javascript/ContentManager/ContentRoute/ContentLayout/ContentLayout.container.jsx
src/javascript/ContentManager/ContentRoute/ContentLayout/ContentLayout.jsx

The size of the Content Tree is now persisted the same way and as the
same lifecycle as the opened/closed status of the Content Tree and
Previewer.

BACKLOG-10740: Use redux to store the size of the Content Tree

---

src/javascript/JContent/ContentRoute/ContentStatuses/ContentStatuses.scss

Unexpected formatting breaks the build since stylelint has been added in between.

BACKLOG-12332: Fix CSS formatting

---

src/javascript/JContent/ContentRoute/ContentStatuses/ContentStatuses.jsx
src/javascript/JContent/ContentRoute/ContentStatuses/ContentStatuses.test.jsx

UNPUBLISHED status should only trigger the rendering of 'Not Published' chip.
https://jira.jahia.org/browse/BACKLOG-12332

BACKLOG-12332: Don't show a 'Warning' chip when a content is UNPUBLISHED

---

src/javascript/JContent/ContentRoute/ContentStatuses/ContentStatuses.container.jsx

UI language was used as an argument to GetContentStatuses query instead of site language.
https://jira.jahia.org/browse/BACKLOG-12332

BACKLOG-12332: Fix incorrect usage of UI language instead of site one

---

src/javascript/JContent/ContentRoute/ContentStatuses/ContentStatuses.gql-queries.js
src/javascript/JContent/ContentRoute/ContentStatuses/ContentStatuses.jsx
src/javascript/JContent/ContentRoute/ContentStatuses/ContentStatuses.test.jsx
src/javascript/JContent/ContentRoute/ContentStatuses/ContentStatuses.utils.js

* Tooltip text of Marked for deletion status for child contents of a deleted one were missing deletion date and user name
* Also fixed incorrect tooltip text from Warning status when publication status is 'mandatoryLanguageValid'
* Rewrote method used to compute status tooltips
https://jira.jahia.org/browse/BACKLOG-12332

BACKLOG-12332: Fix status tooltip of contents marked for deletion

---

src/javascript/JContent/ContentRoute/ToolBar/BrowseControlBar/BrowseControlBar.jsx
src/javascript/utils/getButtonRenderer.jsx

Also removed unnecessary call to react-material's toIconComponent from getButtonRenderer.jsx
https://jira.jahia.org/browse/BACKLOG-12716

BACKLOG-12716: Update buttons size to default in action bar

---

src/javascript/JContent/ContentRoute/ToolBar/FileModeSelector/FileModeSelector.jsx

The icon size now matches the one use for the buttons located on the left side of the header.
https://jira.jahia.org/browse/BACKLOG-12719

BACKLOG-12719: Update icon size

---

src/javascript/JContent/ContentTree/ContentTree.jsx

Root node of pages is hidden, thus when no specific page is selected then there is no visible selected element in the tree view and the header display information about the hidden parent (ie. the site).
From now on, when the root element is selected and this root is not visible, then selection will be forced to its first child (if any) instead.
https://jira.jahia.org/browse/BACKLOG-12530

BACKLOG-12530: Fix non visible node selected in Navigation/TreeView

---

src/javascript/JContent/AppLayout/ContentNavigation/NavigationHeader/SwitchersLayout/LanguageSwitcher.jsx

Languages that are not active for edition should not be selectable from the language switcher.
https://jira.jahia.org/browse/BACKLOG-12802

BACKLOG-12802: Remove unactive languages from language switcher

---

src/javascript/JContent/actions/searchAction/SearchDialog/BasicSearch/BasicSearch.scss

https://jira.jahia.org/browse/BACKLOG-12826
adapt the size of the dropdown menu so it fits long elements

BACKLOG-12826 adapt the size of the dropdown menu so it fits long elements

---

.circleci/config.yml

where the parameter allow to add (or not) the deploy step at the end
https://jira.jahia.org/browse/BACKLOG-12842
As the "mvn deploy" is also running the "install" tasks, having 2 different jobs do not optimize the execution on master. So the idea here is to use a command with a parameter giving the possibility to add the "deploy" step at the end. Note that I had 2 create 2 jobs using almost the same structure because I did not find how to use the branch as a parameter in a workflow job

Optimize the CircleCI configuration

---

src/javascript/JContent/actions/copyPaste/pasteAction.jsx

https://jira.jahia.org/browse/BACKLOG-13028
Separate isVisible and isEnabled status :
- paste is *visible* for content other than pages,  which can have sub nodes (folders, but also content with sub nodes)
- paste is *enabled* when the clipboard content contains something that can be pasted

BACKLOG-13028 : Handle isEnabled/isVisible

---

src/javascript/JContent/ContentRoute/ContentTitle/ContentTitle.jsx

Added attribute to be able to locate header's title from Selenium tests.
https://jira.jahia.org/browse/BACKLOG-12908

BACKLOG-12908: Add selector attribute to header's title

---

src/javascript/JContent/ContentRoute/ToolBar/ToolBar.jsx

Preventing the rendering of the toolbar when data is loading ends-up having the header height being resized while selecting nodes from a content list.
https://jira.jahia.org/browse/BACKLOG-12965

BACKLOG-12965: Don't prevent rendering of toolbar when data is loading

---

src/javascript/JContent/ContentRoute/ToolBar/ToolBar.jsx

Only render publish action once data loading has completed.
Previous fix ([63100abdb9710d7b898557db0e835c791c2b0503](https://github.com/Jahia/jcontent/commit/63100abdb9710d7b898557db0e835c791c2b0503)) to enforce the rendering of the toolbar when data is still loading, did introduce a regression. The publish action button rendered during loading is not re-rendered once loading has completed. Thus correct rendering of the action only occurs if required data was correct on first rendering.
https://jira.jahia.org/browse/BACKLOG-12965

BACKLOG-12965: Fix publishAction not re-rendered once data is loaded

---

src/javascript/JContent/ContentRoute/ContentBreadcrumb/ContentType/ContentType.jsx
src/javascript/JContent/ContentRoute/ContentBreadcrumb/ContentType/ContentType.scss
src/javascript/JContent/ContentRoute/ContentBreadcrumb/ContentType/ContentType.test.jsx

When the breadcrumb does not display any ancestor (ie. it only display the type of the current node) then the header height is reduced by 2 pixels. This changes does fix this issue by adding 1px top and bottom margin around the content type, so that its height matches the one of buttons used for displaying ancestors.
https://jira.jahia.org/browse/BACKLOG-13122

BACKLOG-13122: Prevent header to be resized when breadcrumb is empty

---

src/javascript/JContent.register.jsx
src/javascript/JContent/actions/copyPaste/localStorageHandler.js

https://jira.jahia.org/browse/BACKLOG-12725
initClipboardWatcher was not called anymore, now it's called when opening jContent to watch clipboard if there is any copy action called from pageComposer

BACKLOG-12725 : initClipboardWatcher was not called anymore

---

src/javascript/JContent/ContentRoute/ContentLayout/contentSelection.redux.js

The recently introduced cmSetModePathParams action was not handled.
The issue was only noticeable when using Thumbnail or Detail View in medias section, because List View comes with some specific code to clear the selection.
https://jira.jahia.org/browse/BACKLOG-13138

BACKLOG-13138: Fix selection not always being clear when path is updated

---

src/javascript/JContent/ImageEditor/ImageEditor.container.jsx

https://jira.jahia.org/browse/BACKLOG-12741
Changed snackBarMessage to use jcontent label properly

Fixed label to get localized text properly

---

src/javascript/JContent/ContentNavigation/NavigationHeader/SwitchersLayout/LanguageSwitcher.jsx
src/javascript/JContent/ContentNavigation/NavigationHeader/SwitchersLayout/SiteSwitcher.jsx
src/javascript/JContent/ContentRoute/ContentLayout/ContentListTable/ContentListTable.jsx
src/javascript/JContent/ContentRoute/ContentLayout/contentSelection.redux.js
src/javascript/JContent/ContentRoute/ContentLayout/pagination.redux.js
src/javascript/JContent/JContent.redux.js

https://jira.jahia.org/browse/BACKLOG-13165
Remove listener on redux, update instead reducers so that they react on url change. Removed the actions to update path/mode/params manually, should always go through an url update by using the cmGoto action. The cmGoto actions now build and push the new url , updating all states at once.
Also removed the calls to authoringApi when switching site and language, since this is done in a listener in jahia-ui-root.

BACKLOG-13165: Removed redux listener, use reducers

---

src/main/resources/javascript/locales/de.json

Updated the translation since the button was called differently.

BACKLOG-12739 - Fixed a mismatch between german translation and the actual button name

---

src/javascript/JContent/AdditionalAppsTree/AdditionalAppsTree.jsx

https://jira.jahia.org/browse/BACKLOG-12866
The onClickItem prop for the TreeView component now uses the toggleNode method which is passed through to toggle open/close of the node if it's not selectable as per the data object.
This PR cannot be merged until the supporting change from MOON-131 is included in a Moonstone release.

BACKLOG-12866: Add toggleNode to TreeView onClickItem prop

---

src/javascript/JContent/ContentTree/ContentTree.jsx

https://jira.jahia.org/browse/BACKLOG-13212
Implemented disabling of context menu for menu labels

Implemented disabling of context menu for menu labels

---

src/javascript/JContent/actions/fileUploadAction.jsx

https://jira.jahia.org/browse/QA-12760
use context.id to differentiate upload actions, define useEffect dependencies

QA-12760: use context.id to differentiate upload actions

---

pom.xml

Previous commit removed the Jahia-Deploy-On-Site entry from the MANIFEST because this module was unnecessary deployed on all sites. In order to function properly though, it must at least be deployed on system site.
https://jira.jahia.org/browse/BACKLOG-13685

BACKLOG-13685: Deploy on system site

---

pom.xml

This was set to 1.6.1 by mistake, it should have been 1.7.0

Fixed version for the next release in the 1_x 

---

src/javascript/ContentManager/ContentRoute/ContentLayout/FilesGrid/FileCard/FileCard.jsx

https://jira.jahia.org/browse/BACKLOG-13979
Very simple CSS change to the FileCard to display the background image as "contain" instead of "cover" as the size of the image is always greater than height 200px width 200px (due to the image we are using)
Very simple CSS addition to colour the background colour to #DADADA as per the Figma documentation.
Additional requirement from @fpral to make the thumbnail view to have the same display as well.

BACKLOG-13979: fix card image size and colour 7.3 back porting

---

src/javascript/JContent/actions/deleteActions/deletePermanentlyAction.jsx

https://jira.jahia.org/browse/BACKLOG-23047
Returns the value of the checkAction as a boolean as isAutoPublish can be undefined when the node does not have the jmix:autoPublish property.
If it's the case checkAction returns undefined so isVisible will be equals to undefined and as isVisible is equals to undefined the button will be visible even if it should not.

BACKLOG-23047: return value as boolean in checkAction on delete permanently

---

tests/package.json

following changes in jcontent cypress page object, bump the version of the lib to prepare its publication
related to https://jira.jahia.org/browse/BACKLOG-22873

BACKLOG-22873 : prepare publish of jcontent cypress lib

---

src/javascript/JContent/ContentRoute/ContentLayout/FilesGrid/FilesGrid.scss
src/javascript/utils/NodeIcon.jsx

https://jira.jahia.org/browse/QA-15243
Backport is not compatible with older version of react; returning null crashes thumbnail grid
- Return a default file icon instead of null
- Also fixed thumbnail grid styling https://github.com/Jahia/jcontent/pull/983

QA-15243: Fix issue with returning null NodeIcon; fix thumbnails grid css

---

src/main/java/org/jahia/modules/contenteditor/api/forms/EditorFormServiceImpl.java
src/main/java/org/jahia/modules/contenteditor/api/forms/model/FieldSet.java
tests/cypress/e2e/contentEditor/contentEditorForm.cy.ts
tests/cypress/e2e/contentEditor/textFieldInitializerTest.cy.ts
tests/cypress/page-object/pageComposer.ts
tests/jahia-module/jcontent-test-module/src/main/resources/META-INF/definitions.cnd
tests/jahia-module/jcontent-test-module/src/main/resources/META-INF/jahia-content-editor-forms/forms/jnt_bigText.json

https://jira.jahia.org/browse/BACKLOG-23132
Adding new json override property `isAlwaysActivated` for fieldsets in order to be able to remove fieldset toggle. 
Similar to existing `activatedOnCreate` (https://github.com/Jahia/jcontent/pull/1054) but applied for both edit and create scenarios.
Added cypress test.

BACKLOG-23132: Add isAlwaysActivated fieldset json override property

---

src/javascript/JContent/actions/flushCacheAction/FlushCacheAction.jsx

https://jira.jahia.org/browse/BACKLOG-23210
I added a step to close the flush cache notification popup after 5 seconds ; otherwise the popup stays open until I click somewhere else.

BACKLOG-23210: close notification after 5sec

---

src/javascript/JContent/EditFrame/Boxes.jsx

https://jira.jahia.org/browse/DMF-6381
jExperience has a feature to promote a page variant to the default one in page builder. The promote variant consist in moving the contents of the variant node to the page node and the contents of the page node to the variant node.
When a variant becomes the default one, page builder is refreshed and the default variant is displayed.
At this moment, the boxes in jContent are redrawn but sometimes it's failing because the BoxesQuery returns some old paths. These paths does not match the paths of the the displayed content so the boxes are not displayed correctly.
As it seems to be a cache issue, I changed the fetchPolicy to network-only and it's fixing the issue

DMF-6381: set fetch-policy to network-only on boxes query

---

src/javascript/ContentEditor/SelectorTypes/DateTimePicker/DateTimePicker.jsx
src/javascript/ContentEditor/SelectorTypes/DateTimePicker/DateTimePicker.spec.js
src/main/resources/META-INF/configurations/org.jahia.modules.jcontent.cfg

Provide a way to override date format in date time selector type using a configuration name forceDateFormat (DD/MM/YYYY, MM/DD/YYYY are only valid format)
https://jira.jahia.org/browse/BACKLOG-23452
(Same as https://github.com/Jahia/content-editor/pull/1778 in content editor)

BACKLOG-23452: Provide a way to override date format in date time picker

---

tests/cypress/e2e/jcontent/selection.cy.ts

QABACKLOG-1659: remove duplicate test
The same test was added twice - so one can be removed.
...

QABACKLOG-1659: remove duplicate test

---

src/javascript/ContentEditor/SelectorTypes/DateTimePicker/DateTimePicker.jsx
src/javascript/ContentEditor/SelectorTypes/DateTimePicker/DateTimePicker.spec.js

https://jira.jahia.org/browse/BACKLOG-23452
When a date format is configured in _Jcontent_ (`jcontent.forceDateFormat` property), trim its value ~~and convert it to uppercase,~~ to loose restrictions on this property (as the value **must** be `'MM/DD/YYYY'` or  `'DD/MM/YYYY'`).

BACKLOG-23452: Trim the date format when configured

---

src/javascript/JContent/ContentRoute/ContentRoute.jsx

...
Adding render dialog check is causing some alignment issues in page builder; and also only during tests.
Add/render the dialog component only if there are any render errors.

QA-15374: Add render dialog check only if there is an error

---

src/javascript/JContent/EditFrame/EditFrame.jsx

In jExperience we are using a variant shitcher which allow to switch between variants of the experiences.
When switching between variants, the node might not have the same template.
As the template value can change, the condition frameTemplate !== template can be true. If it's the case, It execute a redirect to the page. 
The problem is that when a redirect is done, the variant switcher is reloaded and reset, so the first variant is dispalyed.
The changes has been included here https://github.com/Jahia/jcontent/pull/1184/files#diff-f3b9133b136957e52dfa17cae204d681b7b8a916ff084e9d4d0302c5f757c288R121
to fix an issue described in https://jira.jahia.org/browse/BACKLOG-21951. 
But I tried to reproduce the issue with the modification done in this PR and the issue is not reproducible. 
I also …

DMF-6407: do not redirect when changing template

---

src/javascript/ContentEditor/registerLegacyGwt.jsx

https://jira.jahia.org/browse/BACKLOG-23547
Fix an error happening when updating the system name of a page model.
The issue happens when the legacy Page Composer is hidden (via the configuration `hideLegacyPageComposer`) as the actions are not registered in this case (see [this line](https://github.com/Jahia/jahia-page-composer/blob/3263d2df1525dfd33460cf96709b01f53d8b6e1d/src/javascript/PageComposer/PageComposer.register.js#L12) in _Page Composer_), leading to a `TypeError`.

BACKLOG-23547: Unable to edit page's system name

---

.github/workflows/release-tests-module.yml
package.json
pom.xml
tests/README.md
tests/package.json

- Create a manual trigger for publishing test module that:
- increments test module version
- create tag and push version change commit to github
- do yarn build and npm publish to npm registry
- Include dryRun flag that disables npm publish (but still pushes commit and tag)
- Added README in `/tests` folder
- Automatically sync test module major version during jcontent releases
- increment of version needs to happen before publish because of this
- Refactored usage of package script as it's not taking into account npm config. Manually execute in bash instead.
- npm config is set up through setup-node action by specifying `registry-url` and `NODE_AUTH_TOKEN` env

fix: Fix workflow for publishing test module

---

package.json
yarn.lock

During a discussion with @GauBen I noticed that jahia-reporter was present as a dependency to content.
jahia-reporter is not needed at this level (only relevant in the context of our Cypress codebases).

chore: removed unnecessary dependency to jahia-reporter

---

package.json
pom.xml
src/javascript/JContent/redux/JContent.redux.js
tests/cypress/e2e/jcontent/navigation.cy.ts
tests/jahia-module/pom.xml
tests/package.json

Currently URLs parsed for `.` extensions to check for any template. This should only apply to viewable contents e.g. when displaying viewable contents. Check that we're applying this only when view is in page builder mode, otherwise redirects when not applicable. 
> [!TIP]

fix: URL parsing for filenames with dot 

---

src/javascript/ContentEditor/utils/fields.utils.js

This ticket to to enable CTOL to clear all properties in all languages at once, as those properties do not show up in nodeData.
> [!TIP]

fix: remove properties with empty values when cannot find it in context

---

pom.xml

Bump jcontent 2.19 to minimum supported version 8.1.7.0

chore: Bump parent version to 8.1.7.0

---

src/javascript/JContent/ContentRoute/ContentLayout/ContentLayout.utils.js
src/javascript/JContent/ContentRoute/ContentLayout/Upload/Upload.utils.js
src/javascript/JContent/dnd/useFileDrop.jsx
tests/cypress/e2e/jcontent/uploadMedia.cy.ts
tests/cypress/page-object/file.ts
tests/cypress/page-object/media.ts

Closes https://github.com/Jahia/jahia-private/issues/3768.
Follows https://github.com/Jahia/jcontent/pull/1911 that only covers the "drag & drop" upload workflow, but not the one with the "Upload file(s)" button (and its dialog).
Refactor the code to use the new `DEFAULT_MIME_TYPE` constant.
Moving `File.dndUploadFromFixtures()` to `Media.uploadFileViaDragAndDrop()` so there is no longer a need to create a (dummy) `File` before being able to drag and drop.
> [!TIP]

fix: Use fallback MIME type when uploading files via dialog

---

tests/package.json

Closes https://github.com/Jahia/javascript-modules/issues/405.
Required by https://github.com/Jahia/jahia-ee/pull/874.
Following the publication of https://www.npmjs.com/package/@jahia/jcontent-cypress/v/3.4.0-tests.3 (done via https://github.com/Jahia/jcontent/actions/runs/16826462538/job/47663985844), merge the bump of version into master  (until https://github.com/Jahia/jcontent/issues/1691 gets addressed).
> [!TIP]

chore: Release JContent test module v3.4.0-tests.3

---

tests/cypress/page-object/fields/choiceListField.ts

Fix the selector used in `ChoiceListField.addNewValue()` that is currently breaking the test `Extend Mixins tests with CE Does not apply extend mixin on create`. See https://github.com/Jahia/jcontent/actions/runs/16782132722/job/47523843006.
In https://github.com/Jahia/jcontent/pull/1941, the following code:
```
getComponentBySelector(Menu, '[role="list"]').selectByValue(value);
```
got replaced by mistake with:
```
getComponentByRole(Menu, 'list').selectByValue(value);
```
Which is a different way to retrieve the component.
> [!TIP]

test: Fix selector in ChoiceListField.addNewValue()
