Jahia/jcontent

src/javascript/ContentManager/ContentRoute/ContentLayout/ResizableDrawer/ResizableDrawer.jsx
src/javascript/ContentManager/ContentRoute/ContentLayout/ResizableDrawer/ResizingHandleBar.jsx

- Fix unexpected text selection when resizing
- Fix iconposition

BACKLOG-10771: Fix resizing handlebar in IE 

---

src/javascript/ContentManager/ContentManager.utils.test.js
src/javascript/ContentManager/ContentManager.utils.test.jsx

https://jira.jahia.org/browse/BACKLOG-11210
add tests for utils functions
no need to test, CMM needs only to build

BACKLOG-11210 : test for utils functions used by zipUnzip actions

---

src/javascript/ContentManager/ContentManager.utils.js

https://jira.jahia.org/browse/BACKLOG-11463
fix counter incrementation

BACKLOG-11463 : fix counter incrementation

---

src/javascript/ContentManager/ContentManager.jsx

BACKLOG-11384 typo

---

src/javascript/ContentManager/ContentRoute/ContentLayout/FilesGrid/FilesGrid.redux-reducer.js

https://jira.jahia.org/browse/QA-12188

QA-12188 : fix little mistake in name of constant

---

src/javascript/ContentManager/ContentRoute/ContentLayout/FilesGrid/FileCard/FileCard.jsx

https://jira.jahia.org/browse/QA-12334

QA-12334 : put a condition to avoid access on undefined object

---

src/javascript/ContentManager/ContentManager.jsx

BACKLOG-11382 execute registered refetch callbacks

---

src/javascript/ContentManager/ContentManager.utils.js
src/javascript/ContentManager/ContentRoute/ContentLayout/ContentListTable/ContentListTable.jsx
src/javascript/ContentManager/ContentRoute/ContentLayout/FilesGrid/FileCard/FileCard.jsx
src/javascript/ContentManager/ContentRoute/ContentLayout/PreviewDrawer/PublicationStatus/PublicationStatus.jsx
src/javascript/ContentManager/ContentRoute/ContentLayout/PublicationStatus/publicationStatusRenderer.jsx

https://jira.jahia.org/browse/QA-12302
adapt CMM to have a default UI language if any of our 3 supported languages is set from the user

QA-12302 : adapt CMM to work with any uiLang

---

pom.xml

https://jira.jahia.org/browse/BACKLOG-11620
is this really necessary here?
Yeah not even talking about this :D

BACKLOG-11620 update dependencies

---

pom.xml
src/javascript/ContentManager/ContentManager.jsx
src/javascript/ContentManager/ContentRoute/ContentLayout/ContentLayout.jsx

https://jira.jahia.org/browse/BACKLOG-11654

Backlog 11654 backport content editor requirements

---

src/main/resources/jnt_template/html/template.content-manager.jsp

https://jira.jahia.org/browse/QA-12400
fix escaping issue, when site display name has a quote 

QA-12400 : fix escaping issue with site display name

---

src/javascript/ContentManager/actions/zipUnzip/unzipAction.jsx

https://jira.jahia.org/browse/BACKLOG-11688 
add a new condition because mimeType in windows is different

BACKLOG-11688 : fix the unzip not appearing issue on windows

---

package.json
webpack.config.js
yarn.lock

https://jira.jahia.org/browse/BACKLOG-12053

BACKLOG-12053 : add case sensitive plugin

---

pom.xml

https://jira.jahia.org/browse/BACKLOG-12057

BACKLOG-12057 : provide i18n resource files in the bundle

---

__mocks__/react-i18next.js
src/javascript/__mocks__/react-i18next.js
src/main/java/org/jahia/modules/contentmanager/actionlists/TagFunctions.java
src/main/resources/META-INF/cm.tld
src/main/resources/javascript/activate-loader.js
src/main/resources/jnt_template/html/template.content-manager.jsp

https://jira.jahia.org/browse/BACKLOG-12113

BACKLOG-12113: Clean useless i18n java code

---

src/javascript/ContentManager/ContentRoute/ContentLayout/EmptyDropZone/EmptyDropZone.jsx
src/javascript/ContentManager/ContentRoute/ContentLayout/Upload/UploadHeader.jsx

https://jira.jahia.org/browse/QA-12555

QA-12555: add namespace to labels when missing

---

src/javascript/ContentManager/ContentRoute/ContentLayout/FilesGrid/FileCard/FileCard.jsx
src/javascript/ContentManager/ContentRoute/ContentLayout/FilesGrid/FilesGrid.jsx

https://jira.jahia.org/browse/BACKLOG-12117

BACKLOG-12117 : navigate with arrows in the thumbnail view

---

src/javascript/ContentManager/ContentRoute/ContentLayout/ContentListTable/ContentListTable.jsx
src/javascript/ContentManager/ContentRoute/ContentLayout/FilesGrid/FilesGrid.jsx
src/javascript/ContentManager/ContentRoute/ContentLayout/useKeyboardNavigation.js

https://jira.jahia.org/browse/BACKLOG-12119

Backlog 12119 navigate with arrow in list view

---

src/main/resources/META-INF/urlrewrite-content-manager.xml

https://jira.jahia.org/browse/BACKLOG-12196

BACKLOG-12196 : fix url redirection

---

src/javascript/JContent/ContentRoute/ContentLayout/ContentListTable/ContentListTable.jsx
src/javascript/JContent/ContentRoute/ContentLayout/FilesGrid/FilesGrid.jsx

https://jira.jahia.org/browse/BACKLOG-12171

BACKLOG-12171: remove blue border while navigating wih arrows

---

src/javascript/JContent/SiteSwitcher/SiteSwitcher.jsx
src/main/resources/META-INF/spring/jcontent.xml

https://jira.jahia.org/browse/BACKLOG-12125

BACKLOG-12125 : replace contentManager permission by editModeAccess

---

src/javascript/JContent/MenuItemRenderer.jsx
src/javascript/JContent/MenuRenderer.jsx

https://jira.jahia.org/browse/BACKLOG-12236

BACKLOG-12236 : add selenium selectors to contextual menu

---

src/javascript/JContent/actions/clearAllLocksAction.jsx
src/javascript/JContentApp.jsx

BACKLOG-12159 : use context attributes from app shell

---

package.json
src/javascript/JContent/AppLayout/AppLayout.container.jsx
src/javascript/JContent/ContentNavigation/ContentNavigation.jsx
src/javascript/JContent/JContent.jsx
src/javascript/JContent/JContentAccordionItems.jsx
yarn.lock

https://jira.jahia.org/browse/BACKLOG-12226

BACKLOG-12226: jContent URLs trigger opening of navigation's accordion

---

src/javascript/register.jsx

https://jira.jahia.org/browse/BACKLOG-12244

BACKLOG-12244 : use callback to register actions

---

package.json
src/javascript/JContent/JContent.jsx
src/javascript/JContent/JContent.redux-store.js
src/javascript/JContent/JContent.redux-utils.js
src/javascript/register.jsx

BACKLOG-12157 : Use redux from app shell

---

src/javascript/JContent/JContent.routes.jsx

BACKLOG-12157 : fixed route

---

src/javascript/JContent/ContentNavigation/ContentNavigation.jsx
src/javascript/JContent/ContentRoute/ContentLayout/ContentLayout.jsx
src/javascript/JContent/ContentRoute/ContentLayout/ContentTrees/ContentTrees.jsx
src/javascript/JContent/JContentAccordionItems.jsx
src/main/resources/META-INF/spring/jcontent.xml

https://jira.jahia.org/browse/BACKLOG-12227

BACKLOG-12227 : old cmm tree in accordions

---

package.json
src/javascript/JContent/JContent.redux-store.js
src/javascript/JContent/JContent.redux-utils.js
yarn.lock

BACKLOG-12158 : Add connected router

---

src/javascript/JContent/JContent.constants.js

https://jira.jahia.org/browse/BACKLOG-12228

BACKLOG-12228 : fix media section

---

src/javascript/JContent/JContentAccordionItems.jsx

https://jira.jahia.org/browse/BACKLOG-12228

BACKLOG-12228 : correct config in accrodion items

---

src/javascript/JContent/AppLayout/AppLayout.container.jsx
src/javascript/JContent/ContentNavigation/ContentNavigation.container.jsx
src/javascript/JContent/ContentNavigation/ContentNavigation.jsx
src/javascript/JContent/ContentNavigation/index.js
src/javascript/JContent/JContent.constants.js
src/javascript/JContent/JContentAccordionItems.jsx

https://jira.jahia.org/browse/BACKLOG-12228

BACKLOG-12228 : fix routes

---

src/javascript/JContent/JContent.redux-store.js

https://jira.jahia.org/browse/BACKLOG-12263
use the right site key to initialize the app

BACKLOG-12263 use the right site key to initialize the app

---

src/javascript/JContent/AppLayout/ContentNavigation/ContentNavigation.container.jsx
src/javascript/JContent/AppLayout/ContentNavigation/ContentNavigation.jsx
src/javascript/JContent/JContent.accordion-items.jsx

https://jira.jahia.org/browse/BACKLOG-12228
fix accordion navigation issue

BACKLOG-12228 fix accordion navigation issue

---

src/javascript/JContent/JContent.app-root.js
src/javascript/JContent/JContent.jsx
src/javascript/register.jsx

https://jira.jahia.org/browse/BACKLOG-12291

BACKLOG-12291 : move app root to registry

---

webpack.config.js

https://jira.jahia.org/browse/BACKLOG-12334
reactivate chunks

BACKLOG-12334 reactivate chunks

---

src/javascript/JContent/JContent.redux.js

https://jira.jahia.org/browse/BACKLOG-12335

BACKLOG-12335 : expose cmGoto

---

jest.config.js
package.json
src/javascript/JContent/AppLayout/ContentNavigation/ContentNavigation.container.jsx
src/javascript/JContent/AppLayout/ContentNavigation/ContentNavigation.jsx
src/javascript/JContent/AppLayout/ContentNavigation/ContentNavigation.test.jsx
src/javascript/JContent/AppLayout/ContentNavigation/NavigationHeader/NavigationHeader.jsx
src/javascript/JContent/ImageEditor/ResizePanel/ResizePanel.test.jsx
src/javascript/__mocks__/react-i18next.js
yarn.lock

https://jira.jahia.org/browse/BACKLOG-12240
Implement integration test with jest and extract access to registry from the ContentNavigation in charge of the display to the container

BACKLOG-12240

---

src/javascript/JContent/ContentRoute/ContentLayout/ContentLayout.container.jsx
src/javascript/JContent/ContentRoute/ContentLayout/ContentTrees/ContentTrees.jsx
src/javascript/JContent/preview.redux.js

BACKLOG-12335: fixed preview

---

src/javascript/JContent/ContentRoute/ContentLayout/ContentTrees/ContentTree/ContentTree.jsx
src/javascript/JContent/ContentRoute/ContentLayout/ContentTrees/ContentTrees.jsx

https://jira.jahia.org/browse/BACKLOG-12343

BACKLOG-12343 : use the new TreeView component

---

src/javascript/JContent/ContentRoute/ContentLayout/contentSelection.redux.js

https://jira.jahia.org/browse/BACKLOG-12386

BACKLOG-12386: Fix broken access to nodes selection.

---

src/javascript/JContent/ContentRoute/ContentLayout/ContentTrees/ContentTree/ContentTree.jsx

https://jira.jahia.org/browse/BACKLOG-12343

BACKLOG-12343 : use icons from registry dynamically

---

src/javascript/JContent/ContentRoute/ContentLayout/ContentTrees/ContentTree/ContentTree.jsx

https://jira.jahia.org/browse/BACKLOG-12423

BACKLOG-12423 : fix grey screen issue when searching

---

src/javascript/JContent/ContentRoute/ToolBar/SearchControlBar/SearchControlBar.jsx
src/javascript/register.jsx

https://jira.jahia.org/browse/BACKLOG-12423

BACKLOG-12423 : get rid of hardcoded browse mode and use our constants

---

src/javascript/JContent/ContentRoute/ToolBar/SearchControlBar/SearchControlBar.jsx

https://jira.jahia.org/browse/BACKLOG-12423

BACKLOG-12423 : fix the path to fix the build

---

package.json
src/javascript/JContent/ContentTree/ContentTree.jsx
src/javascript/JContent/ContentTree/ContentTree.utils.js
yarn.lock

https://jira.jahia.org/browse/BACKLOG-12429

BACKLOG-12429 : update Icons according to the type

---

src/javascript/JContent/JContent.redux.js

https://jira.jahia.org/browse/QA-12619

QA-12619 : fix back button and create content in CE

---

package.json
src/javascript/JContent/AppLayout/ContentNavigation/ContentNavigation.test.jsx
src/javascript/JContent/ContentTree/ContentTree.utils.jsx
src/javascript/JContent/JContent.accordion-items.jsx
src/javascript/register.jsx
yarn.lock

https://jira.jahia.org/browse/MOON-51
Update moonstone version and update icon size due to API change
NOTE: this is breaking accordion Jest test and so the build, but there is a task to fix the accordion so it will fix it too

MOON-51 update moonstone version and update icon size due to API change

---

src/javascript/JContent/ContentTree/ContentTree.utils.jsx
src/javascript/JContent/ContentTree/ContentTree.utils.test.jsx

https://jira.jahia.org/browse/BACKLOG-12396
Jest unit tests

BACKLOG-12396 : unit Test for contentTree.utils functions

---

src/javascript/JContent/AppLayout/ContentNavigation/ContentNavigation.jsx

https://jira.jahia.org/browse/BACKLOG-12434

BACKLOG-12434: Fixed accordion api

---

src/javascript/JContent/ContentTree/ContentTree.utils.jsx

MOON-67 : Use new treeview, open root in files and content

---

src/javascript/JContent/AppLayout/ContentNavigation/ContentNavigation.test.jsx
src/javascript/JContent/JContent.accordion-items.jsx
src/javascript/register.jsx

MOON-51 : removed useless size

---

src/javascript/JContent/MenuItemRenderer.jsx
src/javascript/JContent/MenuRenderer.jsx
src/javascript/JContent/actions/requirementsAction.jsx

BACKLOG-11675 : Handle loading in menu

---

src/javascript/JContent/ContentRoute/ContentTitle/ContentTitle.jsx

https://jira.jahia.org/browse/MOON-48
Updated usage of Moonstone's Typography component to be compatible with new API.

MOON-48: Update variant of Moonstone's Typography components

---

src/javascript/JContent/ContentTree/ContentTree.gql-fragments.js
src/javascript/JContent/ContentTree/ContentTree.jsx
src/javascript/JContent/ContentTree/ContentTree.scss
src/javascript/JContent/ContentTree/ContentTree.utils.jsx

https://jira.jahia.org/browse/BACKLOG-12138

BACKLOG-12138 : Added info in tree for publication / delete / lock

---

src/javascript/JContent/ContentRoute/ToolBar/BrowseControlBar/BrowseControlBar.jsx

BACKLOG-12489 : Use custom renderer

---

src/javascript/JContent/ContentRoute/ToolBar/BrowseControlBar/BrowseControlBar.jsx

https://jira.jahia.org/browse/BACKLOG-12489

BACKLOG-12489 : fix the build

---

src/javascript/JContent/AppLayout/ContentNavigation/NavigationHeader/LanguageSwitcher.jsx
src/javascript/JContent/AppLayout/ContentNavigation/NavigationHeader/SiteSwitcher.jsx

https://jira.jahia.org/browse/BACKLOG-12143

BACKLOG-12143 : keep data-cm-roles as used in selenium

---

package.json
src/javascript/JContent/MenuItemRenderer.jsx
src/javascript/JContent/MenuRenderer.jsx
src/javascript/JContent/actions/requirementsAction.jsx
yarn.lock

BACKLOG-12500 : Use moonstone menu

---

src/javascript/register.jsx

BACKLOG-12533 : Cleaned up primary nav items registration

---

src/javascript/JContent/ContentRoute/ContentLayout/FilesGrid/FileCard/Actions/Actions.jsx
src/javascript/JContent/ContentRoute/ContentLayout/FilesGrid/FileCard/FileCard.jsx

BACKLOG-12493 : Handle actions hover with css

---

package.json
src/javascript/JContent/ContentTree/ContentTree.jsx
src/javascript/JContent/ContentTree/ContentTree.utils.jsx
yarn.lock

https://jira.jahia.org/browse/BACKLOG-12393

BACKLOG-12393 : use useTreeEntries hook

---

src/javascript/JContent/ContentRoute/ContentLayout/ContentListTable/ContentListTable.jsx
src/javascript/JContent/ContentRoute/ContentRoute.jsx
src/javascript/JContent/ContentRoute/ContentStatuses/ContentStatuses.container.jsx
src/javascript/JContent/ContentRoute/ContentStatuses/ContentStatuses.gql-queries.js
src/javascript/JContent/ContentRoute/ContentStatuses/ContentStatuses.jsx
src/javascript/JContent/ContentRoute/ContentStatuses/ContentStatuses.scss
src/javascript/JContent/ContentRoute/ContentStatuses/ContentStatuses.test.jsx
src/javascript/JContent/ContentRoute/ContentStatuses/ContentStatuses.utils.js
src/javascript/JContent/ContentRoute/ContentStatuses/Status.jsx
src/javascript/JContent/ContentRoute/ContentStatuses/Status.test.jsx
src/javascript/JContent/ContentRoute/ContentStatuses/index.js
src/javascript/JContent/JContent.utils.js
src/main/resources/javascript/locales/de.json
src/main/resources/javascript/locales/en.json
src/main/resources/javascript/locales/fr.json

https://jira.jahia.org/browse/BACKLOG-12332

BACKLOG-12332: Add content statuses chips in Header

---

src/javascript/JContent/MenuRenderer.jsx

BACKLOG-12496 : pass anchorEl to menu

---

src/javascript/JContent/ContentRoute/ContentLayout/ContentLayout.container.jsx

BACKLOG-12449 , BACKLOG-12568 :  reverted changes

---

src/javascript/register.jsx

https://jira.jahia.org/browse/BACKLOG-12479
Add role for menu item for QA

BACKLOG-12479 Add role for menu item

---

src/javascript/JContent/ContentRoute/ToolBar/BrowseControlBar/BrowseControlBar.jsx

https://jira.jahia.org/browse/BACKLOG-12282

BACKLOG-12282 : fix disable condition

---

package.json
src/javascript/JContent/ContentTree/ContentTree.jsx
yarn.lock

https://jira.jahia.org/browse/BACKLOG-12602

BACKLOG-12602 : use ContextualMenu in the tree

---

package.json
src/javascript/JContent.register.jsx
src/javascript/index.js

https://jira.jahia.org/browse/BACKLOG-12161

BACKLOG-12161 : use appshell : moved registration in promise

---

src/javascript/JContent/ContentRoute/MainActionBar/MainActionBar.jsx
src/javascript/JContent/JContent.actions.jsx
src/javascript/JContent/MenuItemRenderer.jsx
src/javascript/utils/getButtonRenderer.jsx

BACKLOG-12327

---

src/javascript/JContent/ContentRoute/ToolBar/BrowseControlBar/BrowseControlBar.jsx
src/javascript/JContent/ContentRoute/ToolBar/FileModeSelector/FileModeSelector.jsx
src/javascript/JContent/ContentRoute/ToolBar/ToolBar.jsx
src/javascript/JContent/ContentRoute/ToolBar/Toolbar.scss
src/javascript/JContent/JContent.actions.jsx
src/javascript/JContent/JContent.constants.js
src/main/resources/javascript/locales/de.json
src/main/resources/javascript/locales/en.json
src/main/resources/javascript/locales/fr.json

BACKLOG-12519 : replace files mode switch with buttons

---

src/javascript/JContent/actions/previewAction.jsx

BACKLOG-12561 : Use action component

---

src/javascript/JContent/ContentRoute/MainActionBar/MainActionBar.jsx

https://jira.jahia.org/browse/BACKLOG-12608

BACKLOG-12608 : disable buttons when multiple or single selection

---

src/javascript/JContent/ContentRoute/ToolBar/FileModeSelector/FileModeSelector.jsx

BACKLOG-12611 : added selenium roles

---

src/javascript/JContent/ContentRoute/MainActionBar/MainActionBar.test.jsx

BACKLOG-12669 : Added unit test

---

src/javascript/JContent/ContentRoute/ToolBar/FileModeSelector/FileModeSelector.jsx

BACKLOG-12611 : Added aria attribute

---

src/main/resources/javascript/locales/de.json
src/main/resources/javascript/locales/fr.json

BACKLOG-12689 : added translations

---

src/javascript/JContent/ContentRoute/MainActionBar/MainActionBar.jsx
src/javascript/JContent/JContent.actions.jsx
src/javascript/JContent/JContent.utils.js
src/javascript/JContent/actions/deletePermanentlyAction.jsx
src/javascript/JContent/actions/publishAction.jsx
src/javascript/JContent/actions/publishDeletionAction.jsx
src/javascript/utils/getButtonRenderer.jsx

BACKLOG-12327 : Fixes on publish/unpublish actions

---

src/javascript/JContent/AppLayout/ContentNavigation/NavigationHeader/SwitchersLayout/SwitchersLayout.jsx
src/javascript/JContent/ContentRoute/ToolBar/BrowseControlBar/BrowseControlBar.jsx
src/javascript/JContent/JContent.actions.jsx
src/javascript/JContent/MenuRenderer.jsx

https://jira.jahia.org/browse/BACKLOG-12330

BACKLOG-12330 : fixes in the primaryActions and fix warning

---

src/javascript/JContent/ContentRoute/MainActionBar/MainActionBar.jsx
src/javascript/JContent/actions/publishAction.jsx

BACKLOG-12327 : Fixes issue when node is not available

---

src/javascript/JContent/ContentRoute/ContentLayout/ContentListTable/ContentListTable.jsx

BACKLOG-12327: removed invalid callback

---

src/javascript/JContent/MenuItemRenderer.jsx
src/javascript/utils/getButtonRenderer.jsx

MOON-100 : fixed warnings

---

src/javascript/JContent/ContentRoute/ContentStatuses/ContentStatuses.jsx

https://jira.jahia.org/browse/BACKLOG-12750

BACKLOG-12750: Fix prop type of ancestors property in ContentStatuses

---

src/javascript/JContent/AppLayout/ContentNavigation/NavigationHeader/SwitchersLayout/SiteSwitcher.jsx
src/javascript/JContent/JContent.redux.js

Fix Site Switcher label rednering by displaying selected site displayable name instead of key

Backlog 11237

---

src/javascript/JContent/ContentTree/ContentTree.scss
src/javascript/JContent/ContentTree/ContentTree.utils.jsx
src/javascript/JContent/ContentTree/StatusIcon.jsx

BACKLOG-12278 : Added context menu in tree

---

src/javascript/JContent/ContentTree/ContentTree.gql-fragments.js
src/javascript/JContent/ContentTree/ContentTree.jsx

https://jira.jahia.org/browse/BACKLOG-12764 
Fixes related to https://github.com/Jahia/javascript-components/pull/115

BACKLOG-12764 : update fragments

---

src/javascript/JContent/JContent.redux.js

BACKLOG-12157: Moved redux to appshell

---

src/javascript/JContent/ContentRoute/MainActionBar/MainActionBar.jsx
src/javascript/JContent/ContentRoute/MainActionBar/MainActionBar.test.jsx

BACKLOG-12787

---

src/javascript/JContent/ContentRoute/ContentLayout/Upload/Upload.redux.js

BACKLOG-12443 : Fixed upload

---

src/javascript/JContent/ContentRoute/ContentLayout/ContentLayout.gql-queries.js
src/javascript/JContent/JContent.actions.jsx
src/javascript/JContent/JContent.constants.js
src/javascript/JContent/JContent.redux.js
src/javascript/JContent/actions/searchAction/SearchDialog/BasicSearch/BasicSearch.jsx
src/javascript/JContent/actions/searchAction/SearchDialog/SearchDialog.jsx
src/javascript/JContent/actions/searchAction/searchAction.jsx
src/main/resources/javascript/locales/de.json
src/main/resources/javascript/locales/en.json
src/main/resources/javascript/locales/fr.json

https://jira.jahia.org/browse/BACKLOG-12711
make basic search work with the new search modal

BACKLOG-12711 make basic search work with the new search modal

---

src/javascript/JContent/actions/searchAction/SearchDialog/BasicSearch/BasicSearch.jsx
src/main/resources/javascript/locales/de.json
src/main/resources/javascript/locales/en.json
src/main/resources/javascript/locales/fr.json

https://jira.jahia.org/browse/BACKLOG-12823
add missing all option

BACKLOG-12823 add missing all option

---

src/javascript/JContent/actions/searchAction/SearchDialog/AdvancedSearch/AdvancedSearch.scss
src/javascript/JContent/actions/searchAction/SearchDialog/BasicSearch/BasicSearch.scss
src/javascript/JContent/actions/searchAction/SearchDialog/SearchLocation/SearchLocation.jsx
src/javascript/JContent/actions/searchAction/SearchDialog/SearchLocation/SearchLocation.scss

https://jira.jahia.org/browse/BACKLOG-12710
cosmetic adjustments

BACKLOG-12710 cosmetic adjustments

---

src/javascript/JContent/actions/searchAction/SearchDialog/BasicSearch/BasicSearch.container.jsx
src/javascript/JContent/actions/searchAction/SearchDialog/BasicSearch/BasicSearch.gql-queries.js
src/javascript/JContent/actions/searchAction/SearchDialog/BasicSearch/BasicSearch.jsx
src/javascript/JContent/actions/searchAction/SearchDialog/BasicSearch/BasicSearch.utils.jsx
src/javascript/JContent/actions/searchAction/SearchDialog/BasicSearch/index.js
src/javascript/JContent/actions/searchAction/SearchDialog/SearchDialog.jsx
src/main/resources/javascript/locales/de.json
src/main/resources/javascript/locales/en.json
src/main/resources/javascript/locales/fr.json

https://jira.jahia.org/browse/BACKLOG-12831
sort content type by name
remove node type from the label
reorganize BasicSearch component

BACKLOG-12831 sort content type by name, remove node type from the label, reorganize BasicSearch component

---

src/javascript/JContent/actions/searchAction/SearchDialog/BasicSearch/BasicSearch.test.jsx
src/javascript/JContent/actions/searchAction/SearchDialog/SearchDialog.container.jsx
src/javascript/JContent/actions/searchAction/SearchDialog/SearchDialog.jsx
src/javascript/JContent/actions/searchAction/SearchDialog/SearchDialog.test.jsx
src/javascript/JContent/actions/searchAction/SearchDialog/SearchLocation/SearchLocation.container.jsx
src/javascript/JContent/actions/searchAction/SearchDialog/SearchLocation/SearchLocation.jsx
src/javascript/JContent/actions/searchAction/SearchDialog/SearchLocation/SearchLocation.test.jsx
src/javascript/JContent/actions/searchAction/SearchDialog/SearchLocation/index.js
src/javascript/JContent/actions/searchAction/SearchDialog/index.js
src/javascript/JContent/actions/searchAction/searchAction.jsx

https://jira.jahia.org/browse/BACKLOG-12812
implement tests, refactor components so they can be easily tested

BACKLOG-12812 implement tests, refactor components so they can be easily tested

---

src/javascript/JContent/JContent.actions.jsx
src/javascript/JContent/actions/searchAction/searchAction.jsx

https://jira.jahia.org/browse/BACKLOG-12838
display search on files

BACKLOG-12838 display search on files

---

pom.xml

BACKLOG-12167: rename dx-common-webpack into app-shell

---

.circleci/.circleci.settings.xml
.circleci/config.yml

With this configuration, a branch is only built if there are PR and, on the master only, the deploy has been added as an additional step

[Backlog 12842] Add a CircleCI configuration

---

package.json
src/javascript/JContent/JContent.accordion-items.jsx
yarn.lock

BACKLOG-12865 : Added new icon

---

.circleci/config.yml

https://jira.jahia.org/browse/BACKLOG-12842
Fix the failures on CircleCI by increasing the memory allowed on the docker images

Updated the docker executor to a larger instance

---

src/javascript/JContent/ContentRoute/ContentBreadcrumb/ContentBreadcrumb.jsx
src/javascript/JContent/ContentRoute/ContentBreadcrumb/ContentBreadcrumb.scss
src/javascript/JContent/ContentRoute/ContentBreadcrumb/ContentBreadcrumb.test.jsx
src/javascript/JContent/ContentRoute/ContentBreadcrumb/ContentBreadcrumb.utils.js
src/javascript/JContent/ContentRoute/ContentBreadcrumb/ContentPath/CompositePathEntry.jsx
src/javascript/JContent/ContentRoute/ContentBreadcrumb/ContentPath/CompositePathEntry.test.jsx
src/javascript/JContent/ContentRoute/ContentBreadcrumb/ContentPath/ContentPath.container.jsx
src/javascript/JContent/ContentRoute/ContentBreadcrumb/ContentPath/ContentPath.container.test.jsx
src/javascript/JContent/ContentRoute/ContentBreadcrumb/ContentPath/ContentPath.gql-queries.jsx
src/javascript/JContent/ContentRoute/ContentBreadcrumb/ContentPath/ContentPath.jsx
src/javascript/JContent/ContentRoute/ContentBreadcrumb/ContentPath/ContentPath.test.jsx
src/javascript/JContent/ContentRoute/ContentBreadcrumb/ContentPath/SimplePathEntry.jsx
src/javascript/JContent/ContentRoute/ContentBreadcrumb/ContentPath/SimplePathEntry.test.jsx
src/javascript/JContent/ContentRoute/ContentBreadcrumb/ContentPath/index.js
src/javascript/JContent/ContentRoute/ContentBreadcrumb/ContentType/ContentType.container.jsx
src/javascript/JContent/ContentRoute/ContentBreadcrumb/ContentType/ContentType.container.test.jsx
src/javascript/JContent/ContentRoute/ContentBreadcrumb/ContentType/ContentType.jsx
src/javascript/JContent/ContentRoute/ContentBreadcrumb/ContentType/ContentType.test.jsx
src/javascript/JContent/ContentRoute/ContentBreadcrumb/ContentType/index.js
src/javascript/JContent/ContentRoute/ContentBreadcrumb/index.js
src/javascript/JContent/ContentRoute/ContentHeader/ContentHeader.scss
src/javascript/JContent/ContentRoute/ContentRoute.jsx
src/javascript/JContent/ContentRoute/ContentStatuses/ContentStatuses.scss

https://jira.jahia.org/browse/BACKLOG-12325
Updates related to selenium tests and removal of "old breadcrumb" will be addressed in dedicated pull requests.

BACKLOG-12325: Add new breadcrumb (Moonstone based)

---

src/javascript/JContent/ContentRoute/MainActionBar/MainActionBar.jsx

https://jira.jahia.org/browse/BACKLOG-12854

Respect moonstone or you will pay the price

---

src/main/resources/javascript/locales/de.json
src/main/resources/javascript/locales/en.json
src/main/resources/javascript/locales/fr.json

https://jira.jahia.org/browse/BACKLOG-12926
fix labels

BACKLOG-12926 : fix labels

---

src/javascript/JContent/ContentRoute/ToolBar/BrowseControlBar/BrowseControlBar.jsx
src/javascript/JContent/JContent.actions.jsx
src/javascript/JContent/MenuItemRenderer.jsx
src/javascript/JContent/actions/clearAllLocksAction.jsx
src/javascript/JContent/actions/lockAction.jsx
src/javascript/JContent/actions/unlockAction.jsx

https://jira.jahia.org/browse/BACKLOG-12512
Add the actions menu for the primary actions header, by taking all content actions minus the ones that are displayed. 
Refactored lock/unlock/clear locks actions with compoennts to correctly handle loading and refresh
Cleaned some icons

BACKLOG-12512 : Added additional actions in primary header

---

src/javascript/JContent/ContentNavigation/ContentNavigation.jsx
src/javascript/JContent/JContent.accordion-items.jsx
src/javascript/JContent/JContent.jsx

https://jira.jahia.org/browse/BACKLOG-12938

BACKLOG-12938: Disable additional tab for systemsite

---

.circleci/.circleci.settings.xml

https://jira.jahia.org/browse/BACKLOG-12842
The deploy was not working because of these missing settings

Add the Maven settings to access snapshots

---

src/javascript/JContent.register.jsx
src/javascript/JContent/JContent.redux.js

https://jira.jahia.org/browse/BACKLOG-12914
Build the url from path/mode/params stored in redux

BACKLOG-12914 : Reuse previous lcoation in link

---

src/javascript/JContent/ContentRoute/ToolBar/BrowseControlBar/BrowseControlBar.test.jsx

https://jira.jahia.org/browse/BACKLOG-12945

BACKLOG-12945: Added test

---

src/javascript/JContent/ContentNavigation/ContentNavigation.jsx
src/javascript/JContent/ContentNavigation/ContentNavigation.test.jsx
src/javascript/JContent/JContent.accordion-items.jsx
src/javascript/JContent/JContent.jsx

https://jira.jahia.org/browse/BACKLOG-12980
Do no

BACKLOG-12980: Do not include AccordionItem, makes renderDefaultApps available

---

src/javascript/JContent/ContentRoute/ToolBar/ToolBar.jsx
src/javascript/JContent/ContentRoute/ToolBar/Toolbar.scss
src/javascript/JContent/JContent.actions.jsx
src/javascript/JContent/actions/publishAction.jsx
src/javascript/utils/getButtonRenderer.jsx
src/main/resources/javascript/locales/de.json
src/main/resources/javascript/locales/en.json
src/main/resources/javascript/locales/fr.json

https://jira.jahia.org/browse/BACKLOG-12965

BACKLOG-12965 : fix the sizes

---

src/javascript/JContent/JContent.app-root.js

https://jira.jahia.org/browse/BACKLOG-12229
It's now in jahia-ui-root

BACKLOG-12229 : Moved component renderer out

---

src/javascript/JContent/actions/publishAction.jsx
src/javascript/JContent/actions/publishDeletionAction.jsx

https://jira.jahia.org/browse/BACKLOG-12797
Added publish permission to publication actions.

BACKLOG-12797 Add publish permission to publication actions

---

src/javascript/JContent/ContentRoute/ContentBreadcrumb/ContentBreadcrumb.jsx
src/javascript/JContent/ContentRoute/ContentBreadcrumb/ContentPath/CompositePathEntry.jsx
src/javascript/JContent/ContentRoute/ContentBreadcrumb/ContentPath/SimplePathEntry.jsx

https://jira.jahia.org/browse/BACKLOG-12908
Add some selector attributes to ContentBreadcrumb for Selenium testing.

BACKLOG-12908: Add selector attributes for Selenium testing

---

src/javascript/JContent/ContentRoute/ContentStatuses/ContentStatuses.gql-queries.js
src/javascript/JContent/actions/publishAction.jsx

https://jira.jahia.org/browse/BACKLOG-13021

BACKLOG-13021: Get status for node and subnodes

---

src/javascript/JContent/JContent.actions.jsx
src/javascript/JContent/actions/actions.constants.js
src/javascript/JContent/actions/clearAllLocksAction.jsx
src/javascript/JContent/actions/copyPaste/CopyCutActionComponent.jsx
src/javascript/JContent/actions/copyPaste/pasteAction.jsx
src/javascript/JContent/actions/createFolderAction/createFolderAction.jsx
src/javascript/JContent/actions/deleteAction.jsx
src/javascript/JContent/actions/deletePermanentlyAction.jsx
src/javascript/JContent/actions/downloadFileAction.jsx
src/javascript/JContent/actions/exportAction/exportAction.jsx
src/javascript/JContent/actions/fileUploadAction.jsx
src/javascript/JContent/actions/locateAction.jsx
src/javascript/JContent/actions/lockAction.jsx
src/javascript/JContent/actions/previewAction.jsx
src/javascript/JContent/actions/publishAction.jsx
src/javascript/JContent/actions/publishDeletionAction.jsx
src/javascript/JContent/actions/routerAction.jsx
src/javascript/JContent/actions/subContentsAction.jsx
src/javascript/JContent/actions/undeleteAction.jsx
src/javascript/JContent/actions/unlockAction.jsx
src/javascript/JContent/actions/zipUnzip/unzipAction.jsx
src/javascript/JContent/actions/zipUnzip/zipAction.jsx

https://jira.jahia.org/browse/BACKLOG-13029
Simplified action declaration and include constraints in code :
-Added missing constraints in export 
-Fixed permission on publish action (added start  workflow permission).
-Make publish in all languages invisible if only one language on site instead of disabled.

BACKLOG-13029 : Simplified action declaration and include constraints in code

---

src/javascript/JContent/ContentRoute/ToolBar/ToolBar.jsx
src/javascript/JContent/ContentRoute/ToolBar/Toolbar.test.jsx

https://jira.jahia.org/browse/BACKLOG-13030

BACKLOG-13030: Use short label, switch to publish all for folders

---

src/javascript/JContent/ContentRoute/ContentRoute.jsx
src/javascript/JContent/ContentRoute/ContentSearchTitle/ContentSearchTitle.jsx
src/javascript/JContent/ContentRoute/ContentSearchTitle/ContentSearchTitle.scss
src/javascript/JContent/ContentRoute/ContentSearchTitle/ContentSearchTitle.test.jsx
src/javascript/JContent/ContentRoute/ContentSearchTitle/ContentSearchTitle.test.jsx.disabled
src/javascript/JContent/ContentRoute/ContentSearchTitle/index.js
src/javascript/JContent/ContentRoute/SearchInput/SearchInput.jsx
src/javascript/JContent/ContentRoute/SearchInput/SearchInput.scss
src/javascript/JContent/ContentRoute/SearchInput/index.js
src/javascript/JContent/ContentRoute/ToolBar/SearchControlBar/SearchControlBar.jsx
src/javascript/JContent/actions/searchAction/SearchDialog/SearchDialog.jsx
src/javascript/JContent/actions/searchAction/SearchDialog/SearchDialog.scss
src/javascript/JContent/actions/searchAction/SearchDialog/SearchDialog.test.jsx
src/main/resources/javascript/locales/de.json
src/main/resources/javascript/locales/en.json
src/main/resources/javascript/locales/fr.json

https://jira.jahia.org/browse/BACKLOG-12571
Improve search bar

Backlog 12571

---

src/javascript/JContent/JContent.actions.jsx

https://jira.jahia.org/browse/BACKLOG-13106

BACKLOG-13106: Use a Moonstone icon for undelete action

---

src/main/resources/javascript/locales/de.json

https://jira.jahia.org/browse/BACKLOG-13093
add missing: "lockedBy"

BACKLOG-13093: update json.de

---

src/javascript/JContent/ContentRoute/ContentLayout/ContentLayout.jsx
src/javascript/JContent/ContentRoute/ContentRoute.jsx
src/javascript/JContent/MainLayout/MainLayout.scss

https://jira.jahia.org/browse/BACKLOG-12552

BACKLOG-12552: Fixed layout

---

src/javascript/JContent/actions/copyPaste/pasteAction.jsx
src/javascript/JContent/actions/zipUnzip/unzipAction.jsx
src/javascript/JContent/actions/zipUnzip/zipAction.jsx

https://jira.jahia.org/browse/BACKLOG-13027
prop types not needed at this level, notificationContext is provided by the withNotification hoc

BACKLOG-13027 : Removed warnings

---

src/javascript/JContent/ContentRoute/ContentLayout/PreviewDrawer/Preview/MultipleSelection/MultipleSelection.jsx
src/javascript/JContent/ContentRoute/ContentLayout/PreviewDrawer/Preview/NoPreviewComponent/NoPreviewComponent.jsx
src/javascript/JContent/ContentRoute/ContentLayout/PreviewDrawer/Preview/Preview.jsx
src/javascript/JContent/ContentRoute/ContentLayout/PreviewDrawer/Preview/PreviewComponent/PreviewComponent.container.jsx
src/javascript/JContent/ContentRoute/ContentLayout/PreviewDrawer/PreviewDrawer.jsx
src/javascript/JContent/JContent.redux.js

https://jira.jahia.org/browse/BACKLOG-12394

BACKLOG-12394: Always display a preview when available

---

pom.xml

https://jira.jahia.org/browse/BACKLOG-13114

BACKLOG-13114: Added license check for jcontent

---

package.json
yarn.lock

https://jira.jahia.org/browse/BACKLOG-12854
Just upgrading moonstone

BACKLOG-12854: upgrade moonstone

---

package.json
src/javascript/JContent/AdditionalAppsTree/AdditionalAppsTree.jsx
src/javascript/JContent/ContentTree/ContentTree.utils.jsx
yarn.lock

https://jira.jahia.org/browse/SELENIUM-1027
bump moonstone version and add data-sel-role to tree item

SELENIUM-1027 bump moonstone version and add data-sel-role to tree item

---

src/javascript/JContent/ContentRoute/ContentLayout/EmptyDropZone/EmptyDropZone.jsx
src/main/resources/javascript/locales/de.json
src/main/resources/javascript/locales/en.json
src/main/resources/javascript/locales/fr.json

https://jira.jahia.org/browse/BACKLOG-12739
https://jira.jahia.org/browse/BACKLOG-12686
Fixed labels for page composer and drag and drop with proper icon

Fixed labels for page composer and drag and drop with proper icon

---

pom.xml

Revert "BACKLOG-13114: Added license check for jcontent"

---

src/javascript/JContent.register.jsx

https://jira.jahia.org/browse/BACKLOG-13026
Renamed main route target to have consistent and significant naming. Avoid confusion with nav targets.

BACKLOG-13026: renamed route

---

src/javascript/JContent/ContentRoute/ContentLayout/EmptyDropZone/EmptyDropZone.jsx
src/main/resources/javascript/locales/en.json
src/main/resources/javascript/locales/fr.json

https://jira.jahia.org/browse/BACKLOG-12809
Implemented conditional rendering of the message based on JContent mode

Implemented conditional rendering of the message based on JContent mode

---

src/javascript/JContent.register.jsx

https://jira.jahia.org/browse/BACKLOG-13114

BACKLOG-13114: Check license

---

src/javascript/JContent/JContent.redux.js

https://jira.jahia.org/browse/BACKLOG-13186

BACKLOG-13186: fixed reducer

---

LICENSE.txt
pom.xml
src/main/resources/META-INF/LICENSE.txt

Updated copyright year to 2020

BACKLOG-13160 Update copyright

---

src/javascript/JContent/actions/publishAction.jsx

https://jira.jahia.org/browse/BACKLOG-12797

BACKLOG-12797: Disable buttons when user has no permission

---

src/javascript/JContent/ContentRoute/ContentLayout/Upload/UploadHeader.jsx

https://jira.jahia.org/browse/BACKLOG-12765
https://jira.jahia.org/browse/BACKLOG-13220
Fixed file import label to display properly

Fixed file upload label to display properly

---

pom.xml

Update app-shell dependency

---

src/javascript/JContent/ContentNavigation/NavigationHeader/SwitchersLayout/SiteSwitcher.jsx
src/main/resources/META-INF/configurations/org.jahia.modules.api.permissions-jcontent.cfg

https://jira.jahia.org/browse/BACKLOG-12252

BACKLOG-12252 : renaming of editModeAccess permission

---

src/javascript/JContent.register.jsx

https://jira.jahia.org/browse/BACKLOG-12575
permission name based on https://github.com/Jahia/jahia-private/pull/479

BACKLOG-12575: Added permission check

---

src/javascript/JContent/ContentTree/ContentTree.utils.jsx

https://jira.jahia.org/browse/BACKLOG-13196
Fixed usage of menu-label to grab new section icon from moonstone

Fixed usage of menu-label to grab new section icon from moonstone

---

src/javascript/JContent/actions/downloadFileAction.jsx

https://jira.jahia.org/browse/QA-12760
Use workspace from context to build URL for download

QA-12760: Use workspace from context to build URL for download

---

src/javascript/JContent/ContentTree/ContentTree.utils.jsx

https://jira.jahia.org/browse/BACKLOG-13198

BACKLOG-13198: Add default content icon

---

src/javascript/JContent/ContentTree/ContentTree.jsx
src/javascript/JContent/actions/copyPaste/CopyCutActionComponent.jsx
src/javascript/JContent/actions/copyPaste/pasteAction.jsx
src/javascript/JContent/actions/deleteAction.jsx
src/javascript/JContent/actions/lockAction.jsx
src/javascript/JContent/actions/previewAction.jsx

https://jira.jahia.org/browse/BACKLOG-13212
Disabled actions for menu labels

Disabled actions for menu labels

---

src/main/resources/META-INF/urlrewrite-jcontent.xml

https://jira.jahia.org/browse/QA-12889
Add redirection for old contentmanager links

QA-12889 : Fixed redirections

---

.circleci/.circleci.settings.xml

Update the Maven settings to give CircleCI access to internal repositories (to get artifacts in staging)

Update Maven settings to be able to reach private repositories

---

src/javascript/JContent/JContent.refetches.js
src/javascript/JContent/PushEventHandler/PushEventHandler.jsx
src/javascript/JContent/actions/publishAction.jsx

https://jira.jahia.org/browse/BACKLOG-13227
Register refetch for publish action

BACKLOG-13690 refetch publish action

---

README.md

These shields have generated with https://shields.io/ and are useful to quickly see the status of the repository (build, license, release)

Add shields (CircleCI, last tag) in the README

---

.circleci/.circleci.settings.xml
.circleci/config.yml
.github/workflows/triggerCircleCIOnPR.yml

https://jira.jahia.org/browse/BACKLOG-12265
Improve circle ci configuration, add trigger on PR

BACKLOG-12265 improve circle ci configuration, add trigger on PR

---

src/javascript/ContentManager/ContentManager.actions.jsx

QA-13088: Makes requirementsAction and menuAction available in registry

---

pom.xml

BACKLOG-14378 - Updated Update pom.xml with the new branch name

---

src/javascript/ContentManager/ContentManager.redux-utils.js

https://jira.jahia.org/browse/QA-13346

QA-13346: Avoid url encoding in gwt by using base64

---

package.json
src/javascript/ContentManager/ContentRoute/ContentLayout/ContentLayout.gql-queries.js
src/javascript/ContentManager/ContentRoute/ContentLayout/FilesGrid/FileCard/FileCard.jsx
src/javascript/ContentManager/ContentRoute/ContentLayout/FilesGrid/FileCard/FileSize/FileSize.jsx
src/javascript/ContentManager/ContentRoute/ContentLayout/FilesGrid/FileCard/FileSize/FileSize.test.jsx
src/javascript/ContentManager/ContentRoute/ContentLayout/FilesGrid/FileCard/FileSize/index.js
yarn.lock

Added image weight to the display
Same code changes as https://github.com/Jahia/jcontent/pull/353 but for Jahia 7.3

BACKLOG-13977: Added weight to images for Jahia 7.3

---

package.json
src/javascript/ContentManager/ContentManager.redux-utils.js
yarn.lock

https://jira.jahia.org/browse/BACKLOG-15198
Used space addition to sql2 FROM parameter, which fixes this issue and doesn't break existing functionality, though it's hacky I don't see the reason why encoding/decoding without space doesn't work

BACKLOG-15198 used hack with space in from condition to fix sql2 search

---

src/javascript/ContentManager/ContentManager.actions.jsx

https://jira.jahia.org/browse/QA-13488
Updating the 7.3.8.0 version to be consistent with 8.0.3.0 version.

QA-13488: Allow cut content under pages in jcontent-7.3.8.0

---

package.json
yarn.lock

https://jira.jahia.org/browse/BACKLOG-15946
7.x port for high-severity vulnerabilities fix
8.x PR for reference here: https://github.com/Jahia/jcontent/pull/408

BACKLOG-15946: Fix high sev vulnerabilities (7.x.x)

---

src/javascript/JContent.register.jsx

See [QA-15226](https://jira.jahia.org/browse/QA-15226?focusedId=166191&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-166191) for detailled explaination of this permission check removal.

QA-15226: remove permission check on legacy page composer route, see ticket comments for explaination

---

.github/workflows/release-tests-module.yml

https://jira.jahia.org/browse/BACKLOG-22629
Add tests module release workflow

BACKLOG-22629 Add tests module release workflow

---

src/javascript/JContent/actions/viewUsages.jsx

https://jira.jahia.org/browse/BACKLOG-23045

BACKLOG-23045: Fix max width for usages dialog

---

src/javascript/JContent/PublicationStatus/publicationStatusRenderer.jsx
tests/cypress/e2e/jcontent/publicationStatus.cy.ts

https://jira.jahia.org/browse/QA-15182
This PR fixes the "published by" tooltip in jContent 3 and adds a test case.

QA-15182 Fixed "published by" tooltip

---

package.json
yarn.lock

https://jira.jahia.org/browse/QA-15250
Fix css layout issue on accordion items with dropdown (e.g. site admin accordion) by updating to latest moonstone with fix

QA-15250: Fix accordion item layout CSS

---

src/javascript/ContentEditor/SelectorTypes/Picker/JahiaPicker/RightPanel/PickerContentLayout/PickerContentTable/PickerContentTable.jsx
tests/cypress/e2e/pickers/editorialpicker.cy.ts
tests/cypress/e2e/pickers/pickerTree.cy.ts

https://jira.jahia.org/browse/BACKLOG-23115
This PR removes the sorting option on structured view tables. Also should fix failing jcontent tests.

BACKLOG-23115 Removed sorting on structured views and fixed tests

---

pom.xml

https://jira.jahia.org/browse/BACKLOG-23191

BACKLOG-23191: Bump parent version to 8.1.3.0

---

src/javascript/JContent/ContentRoute/ContentLayout/ContentLayout.jsx
src/javascript/JContent/MainLayout/MainLayout.jsx
src/javascript/JContent/MainLayout/MainLayout.scss

https://jira.jahia.org/browse/QA-15288
2_x backport PR for https://github.com/Jahia/jcontent/pull/822

QA-15288: Fix preview layout for small screens

---

.github/workflows/on-release.yml

https://jira.jahia.org/browse/BACKLOG-22589

BACKLOG-22589: Add missing parameter for the Slack notif

---

.github/workflows/on-release.yml

https://jira.jahia.org/browse/BACKLOG-23191

BACKLOG-23191: Add missing parameter for the Slack notif

---

tests/cypress/e2e/jcontent/mainResource.cy.ts

https://jira.jahia.org/browse/QABACKLOG-1642: add verification to test
These two tests don't check anything about the display of main resources in the left tree currently:
"Should not display main resource in menu"
"Should not display event in content folders menu"
They just expand the left tree. So a verification is added.

QABACKLOG-1642: add verification to test

---

src/javascript/JContent/EditFrame/EditFrame.jsx
src/javascript/JContent/EditFrame/PageHeader/PageHeaderContainer.jsx

https://jira.jahia.org/browse/DMF-6336
Add states to make the switch between variants possible in page builder

DMF-6336: Allow to add additional parameters in edit frame url

---

src/javascript/ContentEditor/editorTabs/EditPanelContent/Preview/PreviewViewers/IframeViewer/IframeViewer.jsx

https://jira.jahia.org/browse/QA-15268
Improve preview in Content Editor

QA-15268: prevent endless loading + improve code on CE preview

---

src/main/resources/META-INF/configurations/org.jahia.modules.jcontent.cfg

Remove default configuration from **forceDateFormat**

BACKLOG-23452: do not provide a configuration for forceDateFormat

---

src/javascript/JContent/EditFrame/EditFrame.jsx
src/javascript/JContent/EditFrame/PageHeader/PageHeaderContainer.jsx
src/javascript/JContent/TransparentLoaderOverlay.jsx

Add extension point to trigger loading from external module

DMF-6383: Add extension point to trigger loading from external module

---

src/javascript/JContent/EditFrame/Box.jsx
src/javascript/JContent/EditFrame/Box.scss
src/javascript/JContent/EditFrame/Boxes.jsx
src/javascript/JContent/EditFrame/Deleted.scss
src/javascript/JContent/EditFrame/DropArea.jsx
src/javascript/JContent/EditFrame/EditFrame.scss

- Design improvement to fit mockups
- Add some animations when a user clicks on a content item
- Clean up CSS

BACKLOG-23427: Design improvements

---

src/javascript/JContent/EditFrame/Box.jsx
src/javascript/JContent/EditFrame/Box.scss

Update header to allow to set its color from external module

DMF-6387: Update header to allow to set its color from external module

---

src/javascript/ContentEditor/SelectorTypes/MultipleLeftRightSelector/MultipleLeftRightSelector.jsx
src/javascript/ContentEditor/SelectorTypes/Picker/Picker.utils.js
tests/cypress/e2e/contentEditor/jsonOverrides/defaultOverrides.cy.ts

Moving from site-settings-seo since we are hiding seo section using default override from jcontent

BACKLOG-23347: Add test for hiding seo section

---

src/main/resources/javascript/locales/de.json
src/main/resources/javascript/locales/fr.json

We are missing a German translation for the "published" status in jContent.

Add German translation for published

---

package.json
yarn.lock

QA-15404 Moonstone version bump to fix long titles

---

src/javascript/JContent/EditFrame/Create.scss

fix: hiding create buttons div (#1463)

---

src/javascript/JContent/ContentRoute/ContentLayout/ContentTable/ContentTable.jsx
src/javascript/JContent/ContentRoute/ContentLayout/ContentTable/reactTable/columns/columns.js
src/javascript/JContent/ContentRoute/ContentLayout/ContentTable/reactTable/components/cells/CellFileSize.jsx
src/javascript/JContent/ContentRoute/ContentLayout/ContentTable/reactTable/components/cells/index.js
src/main/resources/javascript/locales/de.json
src/main/resources/javascript/locales/en.json
src/main/resources/javascript/locales/fr.json

This PR adds a file size column to list view of the media section.
No tests added: we do not have tests for other individual columns.
No documentation to add: no APIs modified, no features changed.
> [!TIP]

feat: file size column for media view

---

tests/cypress/e2e/jcontent/tableViews.cy.ts

Add a simple test to check size file in Media.

test: Add test

---

src/main/resources/javascript/locales/de.json

feat: Add german translation for parent info in tooltip

---

.github/workflows/nightly.yml

There's no need to run the nightly during the weekend and it costs us a few euros for no adding value.
> [!TIP]

feat: do not run nightly during the weekend

---

tests/cypress/e2e/menuActions/reviewer.cy.ts
tests/cypress/e2e/menuActions/visibility.cy.ts

Convert Selenium test testCreateMenuForReviewer into a Cypress test
https://github.com/Jahia/jcontent/issues/1985
> [!TIP]

test: add test for reviewer

---

src/javascript/JContent/CompareDialog/FrameManager/FrameManager.jsx
src/javascript/JContent/JContent.utils.js

Added url parameter hidePersonaPanel to url of the staging/live left iframe's ref
> [!TIP]

fix: Hide persona panel on compare staging/live dialog
